apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: git-repo
  # namespace: dp-pipeline
spec:
  params:
    - name: url
      value: 'https://github.com/cs-tsui/dp-tekton-deploy'
    - name: revision
      value: "master"
  type: git