apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: deploy-dp-pipeline
spec:
  params:
    - name: RELEASE_NAME
      type: string
      default: dp-release
    - name: TARGET_NAMESPACE
      type: string
      default: dp-test
    - name: DP_WORKSPACE_DIR
      description: Location containing configurations
      type: string
      default: dp/basic
    - name: ENV
      type: string
      default: dev
    - name: FIND
      type: string
      default: ''
  resources:
    - name: git-input-source
      type: git
  tasks:
    - name: deploy-capability
      taskRef:
        name: deploy-dp-generic
      params:
        - name: RELEASE_NAME
          value: $(params.RELEASE_NAME)
        - name: TARGET_NAMESPACE
          value: $(params.TARGET_NAMESPACE)
        - name: DP_WORKSPACE_DIR
          value: $(params.DP_WORKSPACE_DIR)
        - name: ENV
          value: $(params.ENV)
        - name: FIND
          value: $(params.FIND)
      resources:
        inputs:
          - name: input-source
            resource: git-input-source
    - name: smoke-test
      timeout: "0h10m00s"
      taskRef:
        name: dp-smoke-test
      params:
        - name: RELEASE_NAME
          value: $(params.RELEASE_NAME)
        - name: TARGET_NAMESPACE
          value: $(params.TARGET_NAMESPACE)
        - name: DP_WORKSPACE_DIR
          value: $(params.DP_WORKSPACE_DIR)
      resources:
        inputs:
          - name: input-source
            resource: git-input-source
      runAfter:
        - deploy-capability