apiVersion: datapower.ibm.com/v1beta1
kind: DataPowerService
metadata:
  name: $(RELEASE_NAME)
  namespace: dp-test
spec:
  license:
    accept: true
    use: production
  resources:
    limits:
      memory: 4Gi
    requests:
      cpu: 4
      memory: 4Gi
  domains:
  - name: "default"
    dpApp:
      config:
      - "default-domain-config"
      # local:
      # - "default-domain-local"
  env:
  - name: DATAPOWER_LOG_LEVEL
    value: "5"
  users:
    - accessLevel: privileged
      name: admin
      passwordSecret: dp-admin-credentials
  version: 10.0.0
  replicas: 1
---
apiVersion: v1
kind: Service
metadata:
  name: $(RELEASE_NAME)-web-svc
  namespace: dp-test
spec:
  selector:
    app.kubernetes.io/instance: dp-test-$(RELEASE_NAME)
  ports:
    - protocol: TCP
      port: 9090
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: $(RELEASE_NAME)-web
  namespace: dp-test
spec:
  to:
    kind: Service
    name: $(RELEASE_NAME)-web-svc
    weight: 100
  port:
    targetPort: 9090
  tls:
    termination: passthrough
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
